# Homework 3

In [78]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


%matplotlib inline

Dataset

In this homework, we will use the California Housing Prices data from Kaggle.

Here's a wget-able link:

wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

We'll keep working with the 'median_house_value' variable, and we'll transform it to a classification task.

In [79]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv')
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

Data preparation

- Select only the features from above and fill in the missing values with 0.
- Create a new column rooms_per_household by dividing the column total_rooms by the column households from dataframe.
- Create a new column bedrooms_per_room by dividing the column total_bedrooms by the column total_rooms from dataframe.
- Create a new column population_per_household by dividing the column population by the column households from dataframe.


In [80]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [81]:
df = df.fillna(0)

In [82]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [83]:
df['rooms_per_household'] = df['total_rooms'] / df['households']
df['rooms_per_household'].head()

0    6.984127
1    6.238137
2    8.288136
3    5.817352
4    6.281853
Name: rooms_per_household, dtype: float64

In [84]:
df['bedrooms_per_room'] = df['total_bedrooms'] / df['total_rooms']
df['bedrooms_per_room'].head()

0    0.146591
1    0.155797
2    0.129516
3    0.184458
4    0.172096
Name: bedrooms_per_room, dtype: float64

In [85]:
df['population_per_household'] = df['population'] / df['households']
df['population_per_household'].head()

0    2.555556
1    2.109842
2    2.802260
3    2.547945
4    2.181467
Name: population_per_household, dtype: float64

Question 1

What is the most frequent observation (mode) for the column ocean_proximity?

In [86]:
df['ocean_proximity'].value_counts()

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

The most frequent observation for ocean_proximity : <1H OCEAN

Split the data

- Split your data in train/val/test sets, with 60%/20%/20% distribution.
- Use Scikit-Learn for that (the train_test_split function) and set the seed to 42.
- Make sure that the target value (median_house_value) is not in your dataframe.


In [87]:
from sklearn.model_selection import train_test_split

In [88]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)

In [89]:
len(df_full_train), len(df_test)

(16512, 4128)

In [90]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

In [91]:
len(df_train),len(df_val), len(df_test)

(12384, 4128, 4128)

In [92]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [93]:
y_train = df_train.median_house_value.values
y_val = df_val.median_house_value.values
y_test = df_test.median_house_value.values

In [94]:
del df_train['median_house_value']
del df_val['median_house_value']
del df_test['median_house_value']

Question 2

- Create the correlation matrix for the numerical features of your train dataset.
    - In a correlation matrix, you compute the correlation coefficient between every pair of features in the dataset.
- What are the two features that have the biggest correlation in this dataset?


In [95]:
df.corr()

longitude  latitude  housing_median_age  \
longitude                  1.000000 -0.924664           -0.108197   
latitude                  -0.924664  1.000000            0.011173   
housing_median_age        -0.108197  0.011173            1.000000   
total_rooms                0.044568 -0.036100           -0.361262   
total_bedrooms             0.068082 -0.065318           -0.317063   
population                 0.099773 -0.108785           -0.296244   
households                 0.055310 -0.071035           -0.302916   
median_income             -0.015176 -0.079809           -0.119034   
median_house_value        -0.045967 -0.144160            0.105623   
rooms_per_household       -0.027540  0.106389           -0.153277   
bedrooms_per_room          0.084836 -0.104112            0.125396   
population_per_household   0.002476  0.002366            0.013191   

                          total_rooms  total_bedrooms  population  households  \
longitude                    0.044568        0.068082    0.099773    0.055310   
latitude                    -0.036100       -0.065318   -0.108785   -0.071035   
housing_median_age          -0.361262       -0.317063   -0.296244   -0.302916   
total_rooms                  1.000000        0.920196    0.857126    0.918484   
total_bedrooms               0.920196        1.000000    0.866266    0.966507   
population                   0.857126        0.866266    1.000000    0.907222   
households                   0.918484        0.966507    0.907222    1.000000   
median_income                0.198050       -0.007295    0.004834    0.013033   
median_house_value           0.134153        0.049148   -0.024650    0.065843   
rooms_per_household          0.133798        0.002717   -0.072213   -0.080598   
bedrooms_per_room           -0.174583        0.122205    0.031397    0.059818   
population_per_household    -0.024581       -0.028019    0.069863   -0.027309   

                          median_income  median_house_value  \
longitude                     -0.015176           -0.045967   
latitude                      -0.079809           -0.144160   
housing_median_age            -0.119034            0.105623   
total_rooms                    0.198050            0.134153   
total_bedrooms                -0.007295            0.049148   
population                     0.004834           -0.024650   
households                     0.013033            0.065843   
median_income                  1.000000            0.688075   
median_house_value             0.688075            1.000000   
rooms_per_household            0.326895            0.151948   
bedrooms_per_room             -0.573836           -0.238759   
population_per_household       0.018766           -0.023737   

                          rooms_per_household  bedrooms_per_room  \
longitude                           -0.027540           0.084836   
latitude                             0.106389          -0.104112   
housing_median_age                  -0.153277           0.125396   
total_rooms                          0.133798          -0.174583   
total_bedrooms                       0.002717           0.122205   
population                          -0.072213           0.031397   
households                          -0.080598           0.059818   
median_income                        0.326895          -0.573836   
median_house_value                   0.151948          -0.238759   
rooms_per_household                  1.000000          -0.387465   
bedrooms_per_room                   -0.387465           1.000000   
population_per_household            -0.004852           0.003047   

                          population_per_household  
longitude                                 0.002476  
latitude                                  0.002366  
housing_median_age                        0.013191  
total_rooms                              -0.024581  
total_bedrooms                           -0.028019  
population                                0.069863 

total_bedrooms & households have the biggest correlation in this dataset.

Make median_house_value binary

- We need to turn the median_house_value variable from numeric into binary.
- Let's create a variable above_average which is 1 if the median_house_value is above its mean value and 0 otherwise.


In [96]:
media = df['median_house_value'].mean()
media

206855.81690891474

In [97]:
above_average = df['median_house_value'] > df['median_house_value'].mean()
above_average = above_average.astype(int)

In [98]:
above_average

0        1
1        1
2        1
3        1
4        1
        ..
20635    0
20636    0
20637    0
20638    0
20639    0
Name: median_house_value, Length: 20640, dtype: int32

Question 3

- Calculate the mutual information score with the (binarized) price for the categorical variable that we have. Use the training set only.
- What is the value of mutual information?
- Round it to 2 decimal digits using round(score, 2)

In [99]:
from sklearn.metrics import mutual_info_score

In [100]:
(y_train > media).astype(int)

array([1, 1, 0, ..., 1, 0, 0])

In [101]:
round(mutual_info_score(df_train.ocean_proximity, (y_train > media).astype(int)),3)

0.101

Question 4

- Now let's train a logistic regression
- Remember that we have one categorical variable ocean_proximity in the data. Include it using one-hot encoding.
- Fit the model on the training dataset.
    - To make sure the results are reproducible across different versions of Scikit-Learn, fit the model with these parameters:
    - model = LogisticRegression(solver="liblinear", C=1.0, max_iter=1000, random_state=42)
- Calculate the accuracy on the validation dataset and round it to 2 decimal digits.


In [102]:
from sklearn.feature_extraction import DictVectorizer

In [103]:
train_dicts = df_train.to_dict(orient = 'records')

In [104]:
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)

In [105]:
val_dicts = df_val.to_dict(orient = 'records')

In [106]:
X_val = dv.transform(val_dicts)

In [107]:
from sklearn.linear_model import LogisticRegression

In [108]:
Y_train = (y_train > media).astype(int)
Y_val = (y_val > media).astype(int)
Y_test = (y_test > media).astype(int)

In [109]:
model = LogisticRegression(solver="liblinear", C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, Y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [110]:
y_pred = model.predict_proba(X_val)[:,1]
y_pred

array([0.08529106, 0.15926791, 0.95290928, ..., 0.95996383, 0.85103103,
       0.4674276 ])

In [111]:
mhv_b = (y_pred >= 0.5)
mhv_b

array([False, False,  True, ...,  True,  True, False])

In [112]:
original_accuracy = round((Y_val == mhv_b).mean(),2)
original_accuracy

0.84

Question 5

- Let's find the least useful feature using the feature elimination technique.
- Train a model with all these features (using the same parameters as in Q4).
- Now exclude each feature from this set and train a model without it. Record the accuracy for each model.
- For each feature, calculate the difference between the original accuracy and the accuracy without the feature.
- Which of following feature has the smallest difference?
    - total_rooms
    - total_bedrooms
    - population
    - households


In [113]:
for i in ['total_rooms','total_bedrooms','population','households']:    
    df_train_tr = df_train.drop(i,axis=1)
    train_tr_dicts = df_train_tr.to_dict(orient = 'records')
    X_train_tr = dv.fit_transform(train_tr_dicts)
    df_val_tr = df_val.drop(i,axis=1)
    val_tr_dicts = df_val_tr.to_dict(orient = 'records')
    X_val_tr = dv.transform(val_tr_dicts)
    model.fit(X_train_tr, Y_train)
    y_pred_tr = model.predict_proba(X_val_tr)[:,1]
    mhv_b_tr = (y_pred_tr >= 0.5)
    tr_accuracy = (Y_val == mhv_b_tr).mean()
    print('Diferencia sin '+i,original_accuracy - tr_accuracy)

Diferencia sin total_rooms 0.003517441860465098
Diferencia sin total_bedrooms 0.004728682170542564
Diferencia sin population 0.013691860465116279
Diferencia sin households 0.006666666666666599


'total_rooms' has the smallest difference

Question 6

- For this question, we'll see how to use a linear regression model from Scikit-Learn
- We'll need to use the original column 'median_house_value'. Apply the logarithmic transformation to this column.
- Fit the Ridge regression model (model = Ridge(alpha=a, solver="sag", random_state=42)) on the training data.
- This model has a parameter alpha. Let's try the following values: [0, 0.01, 0.1, 1, 10]
- Which of these alphas leads to the best RMSE on the validation set? Round your RMSE scores to 3 decimal digits.

If there are multiple options, select the smallest alpha.



In [114]:
from sklearn.linear_model import Ridge

In [115]:
def rmse(y, y_pred):
    error= y - y_pred
    se = error**2
    mse= se.mean()
    return np.sqrt(mse)

In [117]:
for a in [0, 0.01, 0.1, 1, 10]:
    model = Ridge(alpha=a, solver="sag", random_state=42)
    model.fit(X_train, np.log1p(y_train))
    y_pred_ridge = model.predict(X_val)
    print(f'alpha: {a}, RMSE:{round(rmse(np.log1p(y_val),y_pred_ridge),3)}')

alpha: 0, RMSE:0.524
alpha: 0.01, RMSE:0.524
alpha: 0.1, RMSE:0.524
alpha: 1, RMSE:0.524
alpha: 10, RMSE:0.524


There are multiple options, for that reason select the smallest alpha: 0