# Machine Learning Zoomcamp

## 1.8 Linear Algebra Refresh

In [1]:
import numpy as np

In [2]:
u = np.array([2,4,5,6])
u

array([2, 4, 5, 6])

In [43]:
v = np.array([1,0,0,2])
v

array([1, 0, 0, 2])

In [5]:
u + v

array([3, 4, 5, 8])

In [7]:
u * v

array([ 2,  0,  0, 12])

### Multiplication

In [18]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0
    for i in range(n):
        result = result + u[i]* v[i]
    
    return result


In [19]:
vector_vector_multiplication(u,v)

14.0

In [6]:
u.dot(v)

14

In [40]:
U = np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1]])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [41]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)
    
    return result

In [46]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [47]:
U.dot(v)

array([14,  5,  5])

In [48]:
V = np.array([[1,1,2],[0,0.5,1],[0,2,1],[2,1,0]])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [49]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows,num_cols))

    for i in range(num_cols):
        vi = V[:,i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:,i] = Uvi 
    
    return result


In [50]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [51]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Identity matrix

In [60]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [61]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

### Matrix inverse

In [65]:
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])